### ISSUE TITLE
Todo list for my locations app

### ISSUE THREAD

**Issue by gioragutt** [gioragutt/my-locations#1]
# Use cases

> `Manage` = `View, Add, Remove and Edit`

- [x] Manage list of Categories
- [x] Manage list of Locations
- [x] When editing an item (category or location), all fields must be field (required)
- [x] A location must be related to an existing category (`existingCategories.includes(location.category`)
- [x] Each screen must contain top and bottom toolbars
- [x] The bottom toolbar consists of two `icon button`s, one for `Categories` and one for `Location`
  - [x] Clicking a button routes you to the relevant screen
- [x] The top toolbar must consist of a `title` and `action buttons`(`view`, `add`, `remove`)
- [x] Locations are sorted `alphabetically`, optionally grouped by categories
- [x] Location can be filtered by category
- [x] When selecting a location, the user can be redirected to:
  - [x] A screen to view details about a location
  - [x] A map (based) screen on which the user will see a marker representing the location he chose
- [x] While in the map screen, clicking on the map will cause the device to vibrate (via native bridge support)
- [x] *Bonus:* Allow inserting new locations from the map component
  - [x] *Bonus:* Adding a location from the map will suggest an address
  - [x] THE ABOVE WILL NOT WORK IN MOBILE. NO BUILT-IN GESTURE SUPPORT 😠 
- [ ] *Bonus:* Allow relating a `Location` to several categories - update use cases accordingly

# Model Definition

- Category
  - name: `string`
- Location
  - name: `string`
  - address: `string`
  - coordinates: `{ lat: number, long: number }`
  - category: `string`

# Required Technologies

- [x] State Management - `Redux` or `MobX`
- [x] General - use JSX, es2015 with modules (`import & export`)
- [x] Routing - use `react-router`
